### ISSUE TITLE
Override robots.txt crawl-delay

### ISSUE THREAD

**Issue by nacnudus** [dmi3kno/polite#14]
Thanks for this package, it's much easier than following a best-practice guide.

Having said that, would you consider allowing best-practice to be overridden when the user-agent isn't `dmi3kno`?

I'm scraping GOV.UK, which has a [`robots.txt`](https://www.gov.uk/robots.txt) that only sets `crawl-delay` for a specific user agent, but `polite` applies the limit anyway.  If you think this is a bug in the `robotstxt` then apologies, let me know and I'll report it there.

```
User-agent: *
Disallow: /*/print$
# Don't allow indexing of user needs pages
Disallow: /info/*
Sitemap: https://www.gov.uk/sitemap.xml
# https://ahrefs.com/robot/ crawls the site frequently
User-agent: AhrefsBot
Crawl-delay: 10
# https://www.deepcrawl.com/bot/ makes lots of requests. Ideally
# we'd slow it down rather than blocking it but it doesn't mention
# whether or not it supports crawl-delay.
User-agent: deepcrawl
Disallow: /
# Complaints of 429 'Too many requests' seem to be coming from SharePoint servers
# (https://social.msdn.microsoft.com/Forums/en-US/3ea268ed-58a6-4166-ab40-d3f4fc55fef4)
# The robot doesn't recognise its User-Agent string, see the MS support article:
# https://support.microsoft.com/en-us/help/3019711/the-sharepoint-server-crawler-ignores-directives-in-robots-txt
User-agent: MS Search 6.0 Robot
Disallow: /
```

**Comment by dmi3kno** [comment]
Hi and thank you for taking the package for a spin!

You can set your own `user_agent` string using the respective argument to `bow()` which will be used, among other things,  for validation of crawl delay rules against those, yes, reported by `robotstxt` package.

This is what `robotstxt` reports as `crawl_delay` for www.gov.uk:
```r
robotstxt::robotstxt("https://www.gov.uk/")$crawl_delay
#>         field        useragent value
#> 1 Crawl-delay                *    10
#> 2 Crawl-delay        AhrefsBot    10
#> 3 Crawl-delay        deepcrawl    10
#> 4 Crawl-delay MSSearch6.0Robot    10
```
`polite` package is all about compliance, so we simply follow ;) Feel free to file an issue in [robotstxt](https://github.com/ropensci/robotstxt). Folks at ROpenSci turn them around quickly.

**Comment by nacnudus** [comment]
Keeping me honest :wink: 

Here's a [robotstxt issue](https://github.com/ropensci/robotstxt/issues/48).
