### ISSUE TITLE
How about CRAN ?

### ISSUE THREAD

**Issue by cderv** [dmi3kno/polite#17]
Hi, 

this 📦 is really useful. Do you plan to publish to CRAN or is it out of scrope ? 

Thanks !

**Comment by dmi3kno** [comment]
I don't feel I am there yet in terms of completing the functionality and ensuring smooth user experience. I also want to get to 100% test coverage, which includes incorporating tests by `webmockr`. I am very open for any help I can get from the community. Let me know if you're interested in contributing to this package.

**Comment by cderv** [comment]
Nice to know it is planned. I definitely can help if you’re in no rush as I have a few projects right now. 

I will read the code in detail, open some issues and will PR some stuffs when I find time.

**Comment by cderv** [comment]
Glad to know it is on its way ! Thanks.
