### ISSUE TITLE
No scraping allowed here... where to output that?

### ISSUE THREAD

**Issue by maelle** [dmi3kno/polite#2]
I've tested the bow and scrape functions on an URL I knew didn't allow webscraping (I knew it because I had used `robotstxt` on it two days ago) and I was wondering whether it'd make sense for `bow` to already output a message or warning when scraping is not allowed, maybe with a verbose argument? I'm wondering about it because I expected `bow` to tell me "Go away!". 😹 

``` r
notok <- polite::bow("https://www.biodiversitylibrary.org/pageimage")
#> No encoding supplied: defaulting to UTF-8.
polite::scrape(notok)
#> No scraping allowed here!
#> NULL
```

Created on 2018-07-28 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by dmi3kno** [comment]
Great idea, Maelle! Check out the updated version where I warn from `bow` and `nod` (provided `verbose=TRUE` and finally throw an error from `scrape`. 
And thank you for taking package for a spin!
