### ISSUE TITLE
no encoding supplied message

### ISSUE THREAD

**Issue by Aariq** [dmi3kno/polite#25]
When I run bow() I get the following message:
```
No encoding supplied: defaulting to UTF-8.
```

It's not clear from the documentation if there is a way to suppress this message or to supply an encoding.

**Comment by dmi3kno** [comment]
This is something coming from dependency (robotstxt). I filed an issue some time ago. Let me check if it has been solved.

**Comment by dmi3kno** [comment]
Could you please post your `sessionInfo` and provide reproducible example of which site you are getting the warning message at?

**Comment by dmi3kno** [comment]
Fixes have been made in development version of `{robotstxt}`, but never updated on CRAN. I now asked a maintainer if we can expect a CRAN update soon. We will coordinate updates and close this issue as soon as the new version is released. In the meantime, please install dev versions of both packages from Github.

**Comment by Aariq** [comment]
thanks for the update!

**Comment by dmi3kno** [comment]
The issue should be solved now that `robotstxt` new version has been put on CRAN. Please reinstall both packages and try again.
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Thanks <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/CRAN?src=hash&amp;ref_src=twsrc%5Etfw">#CRAN</a>.<br>{robotstxt} 0.7.4 is on its way ... <a href="https://t.co/whZTyjVFwR">https://t.co/whZTyjVFwR</a><br>cc <a href="https://twitter.com/minebocek?ref_src=twsrc%5Etfw">@minebocek</a> <a href="https://twitter.com/dmi3k?ref_src=twsrc%5Etfw">@dmi3k</a> <a href="https://twitter.com/hrbrmstr?ref_src=twsrc%5Etfw">@hrbrmstr</a> <a href="https://twitter.com/rOpenSci?ref_src=twsrc%5Etfw">@rOpenSci</a></p>&mdash; Peter Meissner (@peterlovesdata) <a href="https://twitter.com/peterlovesdata/status/1267809465899929600?ref_src=twsrc%5Etfw">June 2, 2020</a></blockquote>
