### ISSUE TITLE
randomized scrape delay

### ISSUE THREAD

**Issue by Aariq** [dmi3kno/polite#26]
I'm working on a package and other scraping functions (not using polite) use randomized delays like `Sys.sleep(rgamma(1, shape = 5, scale = 1/10))` and I'm wondering if it's possible to replicate that with `polite`.  Is it possible to use `set_scrape_delay()` to set a randomized delay?

**Comment by dmi3kno** [comment]
I am not sure this is in line with the intention of the package. `polite` is pre-occupied with delay being no less than allowable value. Whether or not the delay is random is not a concern that the package is addressing. On the contrary, the intention of the package is to make scraping visible, traceable and predictable (through explicit user-agent string and honouring of robotstxt permissions). 

Today the package is relying on `ratelimitr` for setting the request rate, but I considered going back to `Sys.sleep` or `purrr::slowly()`. The most likely scenario, however, is that I will replace `httr::GET` with `httr::RETRY` which has its own mechanism for request delays through `pause_base`, `pause_cap` and `pause_min` arguments. This will minimize dependencies and simplify code.

Can you make an argument why randomization of the delay rate is desirable feature for `polite` scraping package?

**Comment by Aariq** [comment]
I'm honestly not sure why randomization is desirable at all, but I suspect that it is not in line with the intention of the package.  My guess is that it just makes scraping harder to detect.  Your reply was really helpful though.  I'll look into some of these alternatives.  Thanks for the great package, btw!  Super easy to use!
