### ISSUE TITLE
Polite doesn't seem to work

### ISSUE THREAD

**Issue by giuliogcantone** [dmi3kno/polite#35]
When I try to run the example code:

`session <- bow("https://www.cheese.com/by_type", force = TRUE)
result <- scrape(session, query=list(t="semi-soft", per_page=100)) %>%
  html_node("#main-body") %>% 
  html_nodes("h3") %>% 
  html_text()`

I get this error:

Error in encl$`_hash`(c(encl$`_f_hash`, args, lapply(encl$`_additional`,  : 
  oggetto "rlang_hash" non trovato

**Comment by dmi3kno** [comment]
Works on my computer (c)
``` r
library(polite)
library(rvest)

session <- bow("https://www.cheese.com/by_type", force = TRUE)
result <- scrape(session, query=list(t="semi-soft", per_page=100)) %>% 
  html_node("#main-body") %>% html_nodes("h3") %>% html_text()
str(result)
#>  chr [1:100] "3-Cheese Italian Blend" "Abbaye de Citeaux" ...
```

<sup>Created on 2022-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
