### ISSUE TITLE
default rate limiting

### ISSUE THREAD

**Issue by maelle** [dmi3kno/polite#4]
I'm slowly starting to use `scrape` and was wondering whether the default rate should be a bit lower, e.g. 1 call every 5 seconds?

**Comment by maelle** [comment]
Actually I have a further question/wish, could one set period _in_ bow? So that one could use `scrape` several times using the same session object without worrying about re-inputing period.

**Comment by dmi3kno** [comment]
Agree that 5 sec is a reasonable default. Will move it to `bow()` to keep constant for the session. Great suggestions, Maelle! Thanks a lot!!
