### ISSUE TITLE
first argument in nod

### ISSUE THREAD

**Issue by dmi3kno** [dmi3kno/polite#8]
Maybe first argument in `nod()` should be an argument which could accept either a `polite session` object or url. `Nod` would create/modify `polite session`, but then you could like:

```r
# don't run
url_list %>% 
   walk(~nod(.x) %>% rip()) #or scrape()
```

**Comment by maelle** [comment]
I'm not sure I follow, I'm happy with the `bow` then `scrape` workflow but then I only used it twice (last time yesterday, post to come soon)

**Comment by dmi3kno** [comment]
Never mind. You are right. `bow()` is still a preferred workflow:
```r
# don't run
url_list %>% 
   walk(~bow(.x) %>% rip())
```
